language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

cache:
- directories:
  - "$HOME/emacs"

env:
  global:
    - PATH="$HOME/bin:$PATH"
    - EMAKE_SHA1=d8ab7790f5823547fd4e7aec2218771a3dda0638
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=snapshot

matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot

before_install:
  - wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
  - make -f .travis.mk emacs

script:
  - make -f .travis.mk build/libegit2.so
  - make -f .travis.mk compile
  - make -f .travis.mk test
